# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     Robert-Zacchigna/BlackDoc

# Setup
title:            Robert Zacchigna's Project Portfolio
tagline:          Hire Me
description:      "Posts are organized by year (earliest first), click on the dropdowns to see all of the posts for that year with the most recent post at the top."
github_url:       https://github.com/Robert-Zacchigna/robert-zacchigna.github.io
portfolio_url:    https://github.com/Robert-Zacchigna/Portfolio
permalink:        /:year/:month/:day/:title.html
baseurl:          "/"
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

timezone:         America/Chicago

author:
  name:           Robert Zacchigna
  url:            https://github.com/Robert-Zacchigna/

paginate:         5
paginate_path:    '/post-feed/page-:num/'
                  # Or '/my-jekyll-site/page:num' if you want to move your index pages

# Reading Files
include:
  - _pages
  - post-feed
exlude:
  - LICENSE.md
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-octicons
